/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eczane;


import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sql.rowset.serial.SerialBlob;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Ana_Sayfa extends javax.swing.JFrame {

    /**
     * Creates new form Ana_SAyfa
     */
    public Ana_Sayfa() {
        initComponents();
        Baglanti baglanti = new Baglanti();
        baglanti.getConnection();
        lbl_ID.setVisible(false);
        Tabloda_Goster();
    }
    Baglanti bgl = new Baglanti();
    int sira = 0;
    String resimYolu = null;
    public ImageIcon ResimBoyutlandirma(String resimYol,byte[] resim){
        ImageIcon resmim = null;
        if (resimYol != null) {
            resmim = new ImageIcon(resimYol);
        }
        else {
            resmim = new ImageIcon(resim);
        }
        
        Image resim1 = resmim.getImage();
        Image resim2 = resim1.getScaledInstance(lbl_resim.getWidth(), lbl_resim.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon resim3 = new ImageIcon(resim2);
        return resim3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_Ad = new javax.swing.JTextField();
        txt_Fiyat = new javax.swing.JTextField();
        lbl_resim = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Ilaclar = new javax.swing.JTable();
        btn_Sec = new javax.swing.JButton();
        btn_Ekle = new javax.swing.JButton();
        btn_Sil = new javax.swing.JButton();
        btn_Guncelle = new javax.swing.JButton();
        btn_Onceki = new javax.swing.JButton();
        btn_Ilk = new javax.swing.JButton();
        btn_Sonraki = new javax.swing.JButton();
        btn_Son = new javax.swing.JButton();
        lbl_ID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Ad:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Fiyat:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Resim:");

        txt_Ad.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txt_Fiyat.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lbl_resim.setBackground(new java.awt.Color(255, 255, 204));
        lbl_resim.setOpaque(true);

        tbl_Ilaclar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ad", "Fiyat"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_Ilaclar.setColumnSelectionAllowed(true);
        tbl_Ilaclar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_IlaclarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Ilaclar);
        tbl_Ilaclar.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        if (tbl_Ilaclar.getColumnModel().getColumnCount() > 0) {
            tbl_Ilaclar.getColumnModel().getColumn(0).setHeaderValue("Ad");
            tbl_Ilaclar.getColumnModel().getColumn(1).setHeaderValue("Fiyat");
        }

        btn_Sec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_32_171485.png"))); // NOI18N
        btn_Sec.setText("Resim Seç");
        btn_Sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SecActionPerformed(evt);
            }
        });

        btn_Ekle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-insert-page-16.png"))); // NOI18N
        btn_Ekle.setText("Ekle");
        btn_Ekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_EkleActionPerformed(evt);
            }
        });

        btn_Sil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_Streamline-70_185090.png"))); // NOI18N
        btn_Sil.setText("Sil");
        btn_Sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SilActionPerformed(evt);
            }
        });

        btn_Guncelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_update_172618.png"))); // NOI18N
        btn_Guncelle.setText("Güncelle");
        btn_Guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuncelleActionPerformed(evt);
            }
        });

        btn_Onceki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_back_126585.png"))); // NOI18N
        btn_Onceki.setText("önceki");
        btn_Onceki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OncekiActionPerformed(evt);
            }
        });

        btn_Ilk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_skip-previous_326509.png"))); // NOI18N
        btn_Ilk.setText("ilk");
        btn_Ilk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_IlkActionPerformed(evt);
            }
        });

        btn_Sonraki.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_forward_126569.png"))); // NOI18N
        btn_Sonraki.setText("sonraki");
        btn_Sonraki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SonrakiActionPerformed(evt);
            }
        });

        btn_Son.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/iconfinder_ic_skip_next_48px_352132.png"))); // NOI18N
        btn_Son.setText("son");
        btn_Son.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SonActionPerformed(evt);
            }
        });

        lbl_ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ID.setText("Id");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txt_Fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(txt_Ad, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 38, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Ekle)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Sec, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btn_Sil, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_Guncelle)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_Ilk, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Onceki, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Sonraki, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_Son, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lbl_ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_Ad))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_Fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(lbl_resim, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Onceki)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_Ilk)
                        .addComponent(btn_Sonraki)
                        .addComponent(btn_Son)))
                .addGap(31, 31, 31)
                .addComponent(btn_Sec)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Sil)
                    .addComponent(btn_Guncelle)
                    .addComponent(btn_Ekle))
                .addGap(157, 157, 157))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SecActionPerformed

        // TODO add your handling code here:
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(System.getProperty("user.home")));
       
        FileNameExtensionFilter filter = new FileNameExtensionFilter("*.images", "jpg","png");
        file.addChoosableFileFilter(filter);
        int result = file.showSaveDialog(null);
        if(result == JFileChooser.APPROVE_OPTION)
        {
            File selectedFile = file.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            lbl_resim.setIcon(ResimBoyutlandirma(path, null));
            resimYolu = path;
        }
        else{
            System.out.println("Lütfen seçim yapın");
        }
        
    }//GEN-LAST:event_btn_SecActionPerformed

    private void btn_EkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_EkleActionPerformed
        // TODO add your handling code here:
        Baglanti bgl = new Baglanti();
        if (resimYolu !=null) {
            try {
            String ad = txt_Ad.getText();
            float fiyat = Float.parseFloat(txt_Fiyat.getText()) ;
            InputStream  img = new FileInputStream(new File(resimYolu));
            
            bgl.Ekle(ad,fiyat ,resimYolu);
            JOptionPane.showMessageDialog(null, "Ekleme işlemi başarılı..");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }else{
            JOptionPane.showMessageDialog(null, "Boş geçilmez");
        }
        Tabloda_Goster();
        
    }//GEN-LAST:event_btn_EkleActionPerformed

    private void btn_GuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuncelleActionPerformed
        // TODO add your handling code here:
        Baglanti bgl = new Baglanti();
        if (resimYolu !=null) {
            try {
            String ad = txt_Ad.getText();
            float fiyat = Float.parseFloat(txt_Fiyat.getText()) ;
            InputStream  img = new FileInputStream(new File(resimYolu));
            ilac ilac = new ilac(Integer.parseInt(lbl_ID.getText()),ad,fiyat,resimYolu);
            bgl.Guncelle(ilac);
            JOptionPane.showMessageDialog(null, "Güncelleme işlemi başarılı..");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        }else{
            JOptionPane.showMessageDialog(null, "Boş geçilmez");
        }
        Tabloda_Goster();
    }//GEN-LAST:event_btn_GuncelleActionPerformed

    private void btn_SilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SilActionPerformed
        // TODO add your handling code here:
        if (resimYolu !=null) {
            
            int id = Integer.parseInt(lbl_ID.getText());
            try {
                bgl.Sil(id);
                JOptionPane.showMessageDialog(null, "Silme işlemi başarılı..");
            } catch (SQLException ex) {
                Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Boş geçilmez");
        }
        Tabloda_Goster();
    }//GEN-LAST:event_btn_SilActionPerformed

    private void tbl_IlaclarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_IlaclarMouseClicked
        // TODO add your handling code here:
          int index = tbl_Ilaclar.getSelectedRow();
        try {
            IlacGoster(index);
        } catch (SQLException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tbl_IlaclarMouseClicked

    private void btn_IlkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_IlkActionPerformed
        // TODO add your handling code here:
        sira = 0;
        try {
            IlacGoster(sira);
        } catch (SQLException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_btn_IlkActionPerformed

    private void btn_OncekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OncekiActionPerformed
        // TODO add your handling code here:
        sira--;
       
        if(sira < 0)
        {
            sira = 0;
        }
       
        try {
            IlacGoster(sira);
        } catch (SQLException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_OncekiActionPerformed

    private void btn_SonrakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SonrakiActionPerformed
        // TODO add your handling code here:
        sira++;
       
        if(sira >= bgl.İlaclariGetir().size())
        {
            sira = bgl.İlaclariGetir().size()-1;
        }
       
        try {
            IlacGoster(sira);
        } catch (SQLException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SonrakiActionPerformed

    private void btn_SonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SonActionPerformed
        // TODO add your handling code here:
        sira = bgl.İlaclariGetir().size()-1;
        try {
            IlacGoster(sira);
        } catch (SQLException ex) {
            Logger.getLogger(Ana_Sayfa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_SonActionPerformed

    public void Tabloda_Goster()
    {
        Baglanti bgl = new Baglanti();
        ArrayList<ilac> list = bgl.İlaclariGetir();
        DefaultTableModel model = (DefaultTableModel)tbl_Ilaclar.getModel();
        // clear jtable content
        model.setRowCount(0);
        Object[] row = new Object[4];
        for(int i = 0; i < list.size(); i++)
        {
            
            row[0] = list.get(i).getAdi();
            row[1] = list.get(i).getFiyat();
            
            
            model.addRow(row);
        }
    
    }
    
    public void IlacGoster(int index) throws SQLException
    {
        
        Baglanti bgl = new Baglanti();
        lbl_ID.setText(Integer.toString(bgl.İlaclariGetir().get(index).getId()));
        txt_Ad.setText(bgl.İlaclariGetir().get(index).getAdi());
        txt_Fiyat.setText(Float.toString(bgl.İlaclariGetir().get(index).getFiyat()));
        ImageIcon icon = ResimBoyutlandirma(bgl.İlaclariGetir().get(index).getResim(),null);
        resimYolu = bgl.İlaclariGetir().get(index).getResim();
        lbl_resim.setIcon(icon);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ana_Sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ana_Sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ana_Sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ana_Sayfa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ana_Sayfa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Ekle;
    private javax.swing.JButton btn_Guncelle;
    private javax.swing.JButton btn_Ilk;
    private javax.swing.JButton btn_Onceki;
    private javax.swing.JButton btn_Sec;
    private javax.swing.JButton btn_Sil;
    private javax.swing.JButton btn_Son;
    private javax.swing.JButton btn_Sonraki;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_ID;
    private javax.swing.JLabel lbl_resim;
    private javax.swing.JTable tbl_Ilaclar;
    private javax.swing.JTextField txt_Ad;
    private javax.swing.JTextField txt_Fiyat;
    // End of variables declaration//GEN-END:variables
}
